=== jaimedelgado/JAVA/TI/src/sintaxisXML/visitaExtendida.dtd
<?xml version='1.0' encoding='utf-8' ?>

<!ELEMENT visita (expresionIni?, etapa*, recurso*)> 
<!ATTLIST visita
	id ID #REQUIRED
>
<!ELEMENT expresionIni (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>	
<!ELEMENT etapa (continuacion*|(asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)?)>
<!ATTLIST etapa
	id ID #REQUIRED
	recurso IDREF #REQUIRED
	html CDATA #REQUIRED
>

<!ELEMENT continuacion (precondicion, accion)?>
<!ATTLIST continuacion
	descripcion CDATA #REQUIRED
	etapaSiguiente IDREF #REQUIRED
>
<!ELEMENT recurso EMPTY>
<!ATTLIST recurso
	id ID #REQUIRED
	imagen CDATA #REQUIRED
	descripcion CDATA #REQUIRED
	html CDATA #REQUIRED
>
<!ELEMENT precondicion	(asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>				
<!ELEMENT accion (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT asig (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ATTLIST asig
	variable CDATA #REQUIRED>
<!ELEMENT call ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)+)>
<!ATTLIST call
	nombre CDATA #REQUIRED
	numArgs CDATA #REQUIRED>
<!ELEMENT distinto ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT div ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT igual ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT mayoroigual ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT menor ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT menoroigual ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT mod ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT mul ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT or ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT resta ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT suma ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write), (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))>
<!ELEMENT fun ((param)*,cuerpo)>
<!ATTLIST fun
	nombre CDATA #REQUIRED
	numParams CDATA #REQUIRED>
<!ELEMENT param (#PCDATA)>
<!ELEMENT cuerpo (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT ifthenelse (if, then, else)>
<!ELEMENT if (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT then (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT else (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT not (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT num EMPTY>
<!ATTLIST num
	valor CDATA #REQUIRED>
<!ELEMENT seq ((asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write))*>
<!ATTLIST seq
	numExps CDATA #REQUIRED>
<!ELEMENT var EMPTY>
<!ATTLIST var
	nombre CDATA #REQUIRED>
<!ELEMENT while (condicion, cuerpo)>
<!ELEMENT condicion (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>
<!ELEMENT write (asig|call|distinto|div|igual|mayoroigual|menor|menoroigual|mod|mul|or|resta|suma|fun|ifthenelse|not|num|seq|var|while|write)>

=== jaimedelgado/JAVA/TI/src/sintaxisXML/ejemploExtendido.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Propiedad SYSTEM 'visitaExtendida.dtd'> 
<visita id="visita1">
  <expresionIni>
	<seq numExps="2">
		             <fun nombre="factorial" numParams="1">
		             	<param>n</param>
		             	<cuerpo>
			                <ifthenelse>
			                	<if>
			                       <var nombre="n"/>
			                    </if>
			                    <then>
			                    	<mul>
			                      	 	<var nombre="n"/>
			                      	 	<call nombre="factorial" numArgs="1">
			                      	 		<resta>
			                      	 			<var nombre="n"/>
			                      	 			<num valor="1"/>
			                      	 		</resta>
			                      	 	</call>
			                      	</mul>
			                	</then>
			                	<else>
			                		<num valor="1"/>
			                	</else>
			               </ifthenelse>
			           </cuerpo>
			       </fun>
			       <write>
			     		<call nombre="factorial" numArgs="1">
			     			<num valor="5"/>
			     		</call>
			       </write>
			    </seq>
		</expresionIni>
	<etapa id="WalleNorte" recurso="RWalleNorte" html="index.html">
		<continuacion descripcion="NORTE" etapaSiguiente="WalleNorte">
			<precondicion>
				<seq numExps="2">
		             <fun nombre="factorial" numParams="1">
		             	<param>n</param>
		             	<cuerpo>
			                <ifthenelse>
			                	<if>
			                       <var nombre="n"/>
			                    </if>
			                    <then>
			                    	<mul>
			                      	 	<var nombre="n"/>
			                      	 	<call nombre="factorial" numArgs="1">
			                      	 		<resta>
			                      	 			<var nombre="n"/>
			                      	 			<num valor="1"/>
			                      	 		</resta>
			                      	 	</call>
			                      	</mul>
			                	</then>
			                	<else>
			                		<num valor="1"/>
			                	</else>
			               </ifthenelse>
			           </cuerpo>
			       </fun>
			       <write>
			     		<call nombre="factorial" numArgs="1">
			     			<num valor="5"/>
			     		</call>
			       </write>
			    </seq>
			</precondicion>
			<accion>
				<seq numExps="2">
		             <fun nombre="cuentaAtras" numParams="1">
		             	<param>num</param>
		             	<cuerpo>
			                <seq numExps="1">
			                       <while>
			                       		<condicion>
			                       			<distinto>
			                       				<var nombre="num"/>
			                       				<num valor="0"/>
			                       			</distinto>
			                       		</condicion>
			                       		<cuerpo>
			                       			<seq numExps="2">
			                       				<write>
			                       					<var nombre="num"/>
			                       				</write>
			                       				<asig variable="num">
			                       					<resta>
			                       						<var nombre="num"/>
			                       						<num valor="1"/>
			                       					</resta>
			                       				</asig>
			                       			</seq>
			                       		</cuerpo>
			                       	</while>
			                  </seq>
			              </cuerpo>
			          </fun>
			          <call nombre="cuentaAtras" numArgs="1">
			          		<num valor="6"/>
			          </call>
			     </seq>
			  </accion>
		</continuacion>
		<continuacion descripcion="SUR" etapaSiguiente="WalleSur"/>
		<continuacion descripcion="ESTE" etapaSiguiente="WalleEste"/>
		<continuacion descripcion="OESTE" etapaSiguiente="WalleOeste"/>
	</etapa>
	<etapa id="WalleSur" recurso="RWalleSur" html="EtapaWalleSur.html">
		<continuacion descripcion="NORTE" etapaSiguiente="WalleNorte"/>
		<continuacion descripcion="SUR" etapaSiguiente="WalleSur"/>
		<continuacion descripcion="ESTE" etapaSiguiente="WalleEste"/>
		<continuacion descripcion="OESTE" etapaSiguiente="WalleOeste"/>
	</etapa>
	<etapa id="WalleEste" recurso="RWalleEste" html="EtapaWalleEste.html">
		<continuacion descripcion="NORTE" etapaSiguiente="WalleNorte"/>
		<continuacion descripcion="SUR" etapaSiguiente="WalleSur"/>
		<continuacion descripcion="ESTE" etapaSiguiente="WalleEste"/>
		<continuacion descripcion="OESTE" etapaSiguiente="WalleOeste"/>
	</etapa>
	<etapa id="WalleOeste" recurso="RWalleOeste" html="EtapaWalleOeste.html">
		<continuacion descripcion="NORTE" etapaSiguiente="WalleNorte"/>
		<continuacion descripcion="SUR" etapaSiguiente="WalleSur"/>
		<continuacion descripcion="ESTE" etapaSiguiente="WalleEste"/>
		<continuacion descripcion="OESTE" etapaSiguiente="WalleOeste"/>
	</etapa>
	<recurso id="RWalleNorte" descripcion="Walle-Norte" imagen="walleNorth.png" html="RWalleNorte.html"/>
	<recurso id="RWalleSur" descripcion="Walle-Sur" imagen="walleSouth.png" html="RWalleSur.html"/>
	<recurso id="RWalleEste" descripcion="Walle-Este" imagen="walleEast.png" html="RWalleEste.html" />
	<recurso id="RWalleOeste" descripcion="Walle-Oeste" imagen="walleWest.png" html="RWalleOeste.html"/>
</visita>
